version: "2"

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - errorlint
    - gocritic
    - unconvert
    - wastedassign
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gosec:
    excludes:
      - G104
      - G107

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
