version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - errorlint
    - gocritic
    - unconvert
    - wastedassign
    - misspell

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
