name: CI

on:
  push:
    # run CI only for main and dev branches
    branches: [ 'main', 'dev' ]
  pull_request:
    # run CI for PRs targeting main and dev
    branches: [ 'main', 'dev' ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    strategy:
      matrix:
        go: [ '1.25.0' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-modules-${{ hashFiles('apps/backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-modules-

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Prepare module
        run: |
          echo "Current directory: $(pwd)"
          echo "Go version: $(go version)"
          go env -w GOPROXY=https://proxy.golang.org,direct
          go mod download
          go mod verify
          echo "Module download complete"

      - name: Verify critical imports
        run: |
          echo "Checking critical imports in go.mod..."
          for pkg in "github.com/labstack/echo/v4" "github.com/clerk/clerk-sdk-go/v2" "github.com/go-playground/validator/v10" "github.com/jackc/pgx/v5" "github.com/redis/go-redis/v9"; do
            if grep -q "$pkg" go.mod; then
              echo "✓ $pkg present"
            else
              echo "✗ $pkg MISSING"
              exit 1
            fi
          done
          echo "Listing downloaded modules..."
          go list -m all | head -20

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "gofmt found issues:" && gofmt -l .
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          working-directory: apps/backend
          args: --config .golangci.yml --timeout 5m

      - name: Govulncheck (vuln scan for Go modules)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec (security checks)
        run: |
          gosec ./...

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test ./... -v

      - name: Build binary
        run: |
          mkdir -p bin
          go build -o bin/server ./cmd/go-boilerplate

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-go${{ matrix.go }}
          path: apps/backend/bin/server
